# backend/Dockerfile.bff
FROM golang:1.25-alpine AS builder

# Install build dependencies
RUN apk add --no-cache build-base

WORKDIR /app

# Copy dependency definitions
COPY go.mod go.sum ./
RUN go mod download

# Copy shared internal code
COPY internal ./internal

# Copy service-specific code
COPY cmd/bff ./cmd/bff

# Build the binary
ENV CGO_ENABLED=1
RUN go build -o /bin/bff ./cmd/bff/handlers.go ./cmd/bff/main.go

# Final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /app
COPY --from=builder /bin/bff /app/bff

# Expose port
EXPOSE 8080

CMD ["/app/bff"]
